#!/bin/bash -e

trap 'echo "ERROR: $BASH_SOURCE:$LINENO $BASH_COMMAND" >&2' ERR

if [ "${LOG_TO_STDOUT}" != "1" ]; then
  mkdir -p /var/log/powerdns
  chown nobody:nogroup /var/log/powerdns

  exec chpst -u nobody:nogroup svlogd -tt /var/log/powerdns
else
  exec chpst -u nobody:nogroup regex2json "^\\s*(?:(?P<time___time__Stamp___optional>\\S+ \\d+ \\d+:\\d+:\\d+) )?(?:\\[(?P<c___optional>[^\\]]+)\\] )?(?P<msg>.+?)\\s*$"
fi
