#!/bin/bash -e

if [ "${LOG_TO_STDOUT}" != "1" ]; then
  mkdir -p /var/log/powerdns
  chown nobody:nogroup /var/log/powerdns

  exec chpst -u nobody:nogroup svlogd -tt /var/log/powerdns
else
  exec chpst -u nobody:nogroup regex2json "^\\s*(?(?P<time___optional>\\S+ \\d+ \\d+:\\d+:\\d+) )?(?P<msg>.+?)\\s*$"
fi
